import '../styles/globals.css'
import Head from 'next/head'
function MyApp({ Component, pageProps }) {
  return<>
  <Head>
        <title>NwesApp </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"></link>
  </Head >
  <h1>Noticias👀</h1>
  <h2>Noticias👀</h2>
  <Component {...pageProps} />
  </>
}

export default MyApp
